title: Izaan Shaikh # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/izaanshaikh/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-GN2NYQJ027 # your Google Analytics tracking ID here
